### ISSUE TITLE
Função que remova marcação da Luci do texto

### ISSUE THREAD

**Issue by brunolcarli** [brunolcarli/Luci#14]
para interpretar o texto, os algoritmos precisam receber um texto puro.  A menção da *tag* discord da Luci não pode estar presente.

A tag da Luci pode aparecer nem diferentes formatos dependendo da interface e versão da interface de onde a mensagemd e entrada está sendo encaminhada, dentre os padrões:

`<@!720467344182345739>`

`<@720467344182345739>`

Onde `720467344182345739` é o id do bot que deve ser removido da string. A função pode ficar no [módulo de utilitários](https://github.com/brunolcarli/Luci/blob/master/core/utils.py), deve receber uma string como argumento, vasculhá-la, remover o ID e devolver a string.

```python
def function_name(string):
    # remove luci mention from string
    return string
```

**Comment by Zpring** [comment]
Uma alternativa poderia ser utilizar Regex na função de tratamento da String removendo o conteúdo presente dentro dos delimitadores "<" e ">" e o próprio delimitador.

```python
import re

def remove_id(string):
    """
    Remove caracteres presentes dentro dos delimitadores "<" e ">"
    """
    string = re.sub(r'<(?<=\<)(.*?)(?=\>)>', '', string)

    return string
```

Saída:
```
>>> remove_id("<@720467344182345739> Quantos anos você tem?")
>>>  Quantos anos você tem?
```

**Comment by brunolcarli** [comment]
Sim, perfeito, usar regex é uma solução perfeitamente viável 👍
