### ISSUE TITLE
Adicionar passo-a-passo (tutorial)

### ISSUE THREAD

**Issue by brunodpoliveira** [brunolcarli/Luci#34]
Olá. Sugiro que seja criado um tutorial, com um passo-a-passo de como rodar a Luci. (e.g Acionar a Luci, o Jion, sincronizar a database, etc.) A maioria disso já está no canal do Discord, mas seria bom colocar essas instruções aqui.

**Comment by brunolcarli** [comment]
https://github.com/brunolcarli/Luci/wiki/Instala%C3%A7%C3%A3o-e-execu%C3%A7%C3%A3o
